version: '2'
services:
  web:
    build: .
    volumes:
      - .:/app
    depends_on:
      - postgres
    ports:
      - 8080:8080
  postgres:
    container_name: postgres
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=memories
    ports:
      - 5432:5432
